name: health-fitness-tracker
services:
  - name: backend
    path: fitness-health-backend
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    routes:
      - path: /api/*
        preserve_path: true

  - name: frontend
    path: fitness-tracker-frontend
    build_command: npm install
    run_command: npm run build
    environment_slug: node-js
    static_sites:
      - path: /
        build_output: /build
